import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";

const carbonaSans = Inter({
  variable: "--font-carbona-sans",
  subsets: ["latin"],
});

const carbonaMono = Roboto_Mono({
  variable: "--font-carbona-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="scroll-smooth">
      <body className={`${carbonaSans.variable} ${carbonaMono.variable}`}>
        <div className="bg-background min-h-screen">{children}</div>
        {/* <Toaster richColors /> */}
      </body>
    </html>
  );
}
